---
title: "COVID19 project"
author: "Michal Graziowski"
date: "`r format(Sys.time(), '%d.%m.%Y')`r"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(plotly)
library(corrplot)
library(caret)
```

```{r load data, include=FALSE}
original_data <- read_excel("./wuhan_blood_sample_data_Jan_Feb_2020.xlsx")
```

```{r tranform data, include=FALSE}
# merged cells have empty value, thus Patients ids are mostly NA.

df <- original_data %>% 
  rename_with(function(name) toupper(str_replace_all(name, " ", "_"))) %>%
  tidyr::fill(PATIENT_ID) %>%
  group_by(PATIENT_ID) %T>%
  {options(warn=-1)} %>% # some encoding issues
  summarise(across(!RE_DATE, mean, na.rm=TRUE), .groups = "keep")  %T>%
  {options(warn=0)} %>%
  ungroup() %>%
  mutate(GENDER = if_else(GENDER == 1, "MALE", "FEMALE"))

df$"2019-NCOV_NUCLEIC_ACID_DETECTION" <- df$"2019-NCOV_NUCLEIC_ACID_DETECTION" %>%
  replace_na(1)

df <- df %>%
  mutate(HAS_SURVIVED = if_else(OUTCOME == 1, FALSE, TRUE), .after="OUTCOME") %>%
  mutate(DAYS_COUNT =  as.numeric(as.Date(DISCHARGE_TIME) - as.Date(ADMISSION_TIME)), .after="PATIENT_ID") %>%
  select(!c(ADMISSION_TIME, OUTCOME)) %>%
  mutate_all(~if_else(is.na(.), median(., na.rm = TRUE), .))

names(df) <- make.names(names(df),unique = TRUE)
```

# Executive summary
Bla Bla Bla

# Used libraries
* `readxl`
* `dplyr`
* `tidyr`
* `stringr`
* `ggplot2`
* `plotly`
* `corrplot`
* `caret`

# Dataset description

# Statistics
## Overall fatality
```{r overall fatality, echo=FALSE}
dfByOutcome <- df %>%
  group_by(HAS_SURVIVED) %>%
  tally(name="COUNT")


graph <- ggplot(
  dfByOutcome,
  aes(x=HAS_SURVIVED, y=COUNT, fill=HAS_SURVIVED)
) +
  geom_bar(stat="identity",
  position="identity") +
  theme_classic()

ggplotly(graph)
```

## Gender based
```{r division by gender, echo=FALSE}
dfByGender <- df %>%
  group_by(GENDER) %>%
  tally(name="COUNT")


graph <- ggplot(
  dfByGender,
  aes(x=GENDER, y=COUNT, fill=GENDER)
) +
  geom_bar(stat="identity",
  position="identity") +
  theme_classic()

ggplotly(graph)
```

```{r outcomes by gender, echo=FALSE, warning=FALSE}
fatalityByGender <- df %>%
  group_by(GENDER, HAS_SURVIVED) %>%
  tally(name="COUNT")

graph <- ggplot(fatalityByGender, aes(x=HAS_SURVIVED, y=COUNT, fill=HAS_SURVIVED))+
  geom_bar(stat='identity')+
  facet_wrap(~GENDER) +
  theme_classic()

ggplotly(graph)
```

## By Age
```{r histogram by age, echo=FALSE}
graph <-ggplot(df, aes(x=AGE, fill=GENDER)) + 
  geom_histogram(color="black", binwidth=5, alpha=0.5, position="identity") +
  theme_classic()

ggplotly(graph)
```

```{r histogram of those who didnt survive by age, echo=FALSE, warning=FALSE}
graph <-ggplot(df %>% filter(HAS_SURVIVED == FALSE), aes(x=AGE)) + 
  geom_histogram(color="black", binwidth=5, position="identity")+
  theme_classic()

ggplotly(graph)
```

```{r histogram of those who didnt survive by age and gender, echo=FALSE, warning=FALSE}
graph <-ggplot(df %>% filter(HAS_SURVIVED == FALSE), aes(x=AGE, fill=GENDER)) + 
  geom_histogram(color="black", binwidth=5, alpha=0.5, position="identity")

ggplotly(graph)
```

## By days in the hospital
```{r histogram by days count, echo=FALSE}
graph <-ggplot(df, aes(x=DAYS_COUNT, fill=GENDER)) + 
  geom_histogram(color="black", binwidth=3, alpha=0.5, position="identity") +
  theme_classic()

ggplotly(graph)
```

```{r propability of death by the days count, echo=FALSE}
maxDaysNumber <- max(df$DAYS_COUNT)
binWidth = 3
buckets <- seq(0, maxDaysNumber, binWidth)

allPatientsInDaysBin <- df %>%
  select(c(PATIENT_ID, DAYS_COUNT)) %>%
  mutate(DAYS_BIN = DAYS_COUNT - DAYS_COUNT %% binWidth) %>%
  group_by(DAYS_BIN) %>%
  count(DAYS_BIN, name = "ALL_COUNT")

deadPatientsInDaysBin <- df %>%
  filter(HAS_SURVIVED == FALSE) %>%
  select(c(PATIENT_ID, DAYS_COUNT)) %>%
  mutate(DAYS_BIN = DAYS_COUNT - DAYS_COUNT %% binWidth) %>%
  group_by(DAYS_BIN) %>%
  count(DAYS_BIN, name = "DEAD_COUNT")

probabilityOfDeath <- left_join(allPatientsInDaysBin, deadPatientsInDaysBin, by = "DAYS_BIN") %>%
  mutate(DEAD_COUNT = replace_na(DEAD_COUNT, 0)) %>%
  mutate(PROPABILITY = DEAD_COUNT / ALL_COUNT)


graph <-ggplot(probabilityOfDeath, aes(x=DAYS_BIN, y=PROPABILITY)) +
  geom_line() +
  theme_classic()

ggplotly(graph)
  
```

# Correlation between selected attributes
``` {r correlation between selected attributes, echo=FALSE}
dataForCorelation <- df %>%
  mutate(GENDER = if_else(GENDER == "MALE", 1, 0)) %>%
  mutate(LYMPHOCYTES = LYMPHOCYTE_COUNT) %>%
  mutate(CRP = df$"HIGH_SENSITIVITY_C.REACTIVE_PROTEIN") %>%
  mutate(LDH = LACTATE_DEHYDROGENASE)  %>%
  mutate(NCOV_NUCLEIC = df$"X2019.NCOV_NUCLEIC_ACID_DETECTION") %>%
  select(c(HAS_SURVIVED, GENDER, DAYS_COUNT, LDH, LYMPHOCYTES, CRP, NCOV_NUCLEIC)) %>%
  mutate_all(~if_else(is.na(.), median(., na.rm = TRUE), .))

dataForCorelation <- cor(dataForCorelation)[2:7,1, drop=FALSE]
  
corrplot(dataForCorelation,
         method = "circle",
         tl.col = "black",
         insig = "blank",
         title = "Correlation between death and selected features",
         mar = c(0,0,1,0),
         number.cex=2,
        number.font = 1)
```

# Amount of Deaths/Survivors over time
``` {r statistics over time, echo=FALSE}
data <- df %>%
  arrange(DISCHARGE_TIME) %>%
  select(DISCHARGE_TIME, HAS_SURVIVED)
  

graph <- ggplot(data, aes(DISCHARGE_TIME)) +
  xlab("date") +
  ylab("sum of people") +
  geom_line(aes(y=cumsum(HAS_SURVIVED), color=TRUE)) +
  geom_line(aes(y=cumsum(!HAS_SURVIVED), color=FALSE))

graph$labels$colour <- "Has Survived"

ggplotly(graph)

```

# Classification
``` {r classifaction, echo=FALSE}
# set.seed(32)
# 
# data <- df %>%
#   mutate(HAS_SURVIVED = if_else(HAS_SURVIVED, "ALIVE", "DEAD")) %>%
#   mutate(HAS_SURVIVED = as.factor(HAS_SURVIVED)) %>%
#   select(-PATIENT_ID)
# 
# inTraining <- 
#     createDataPartition(
#         # atrybut do stratyfikacji
#         y = df$HAS_SURVIVED,
#         # procent w zbiorze uczącym
#         p = .75,
#         # chcemy indeksy a nie listę
#         list = FALSE)
# 
# training <- data[ inTraining,]
# testing  <- data[-inTraining,]
# 
# rf_grid <- expand.grid(mtry = 2:20)
# 
# control <- trainControl(
#     method='repeatedcv', 
#     number=10, 
#     repeats=5)
# 
# fit <- train(
#     HAS_SURVIVED ~ .,
#     data=training, 
#     method='rf', 
#     trControl=control,
#     tuneGrid=rf_grid,
#     ntree = 10)
# 
# rfClasses <- predict(fit, newdata = testing)
# confusionMatrix(rfClasses, testing$HAS_SURVIVED)
# print(varImp(fit, scale=FALSE))
```